# Generated by Django 4.1.2 on 2022-10-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='featured_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='Promotions',
            field=models.ManyToManyField(null=True, to='store.promotion'),
        ),
    ]
