# Generated by Django 4.1.2 on 2022-10-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_collection_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Promotions',
            field=models.ManyToManyField(to='store.promotion'),
        ),
    ]
