# Generated by Django 4.1.2 on 2022-10-29 07:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_promotions_product_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='title'),
            preserve_default=False,
        ),
    ]
