# Generated by Django 4.1.2 on 2022-10-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_collection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
    ]
