# Generated by Django 4.1.2 on 2022-10-30 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_collection_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='slug',
        ),
    ]
