# Generated by Django 4.1.2 on 2022-10-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_collection_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Qty',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
